Look for and use the enhanced GNU getopt command

diff --git a/git-hooks b/git-hooks
--- a/git-hooks
+++ b/git-hooks
@@ -24,6 +24,20 @@ GITHOOKS=(
     post-rewrite
 )
 
+set +e
+getopt -T &>/dev/null
+set -e
+if [[ $? -eq 4 ]]; then
+    getopt=getopt
+else
+    getopt="$(brew --prefix gnu-getopt &>/dev/null || command -v port &>/dev/null && echo /opt/local || echo /usr/local)/bin/getopt"
+fi
+
+if !command -v $getopt &>/dev/null ; then
+    echo "Could not find GNU getopt. Exiting." >&2
+    exit 1
+fi
+
 # HELP
 #############################################
 read -r -d '' HELP <<'HELP' || :
@@ -232,7 +246,7 @@ function git_hooks__extract_help {
 function git_hooks__extract_doc {
     local doc_type
 
-    eval set -- "$(getopt -o ah -- $@)"
+    eval set -- "$($getopt -o ah -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -a) doc_type=ARGS; shift;;
@@ -286,7 +300,7 @@ HELP
 
     local link item answer firsttime examples=false no_preserve=false
 
-    eval set -- "$(getopt -o e --long examples,no-preserve -- $@)"
+    eval set -- "$($getopt -o e --long examples,no-preserve -- $@)"
     while [[ $1 != -- ]]; do
         case $1 in
             -e|--examples) examples=true; shift;;
@@ -732,7 +746,7 @@ HELP
 
     local name quiet=false
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o q --long quiet -- "$@")"
     while [[ $1 != -- ]]; do
         case $1 in
             -q|--quiet) quiet=true; shift;;
@@ -766,7 +780,7 @@ HELP
 
     local name quiet=false
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o q --long quiet -- "$@")"
     while [[ $1 != -- ]]; do
         case $1 in
             -q|--quiet) quiet=true; shift;;
@@ -799,7 +813,7 @@ HELP
 
     local hook name path
 
-    eval set -- "$(getopt -o q --long quiet -- "$@")"
+    eval set -- "$($getopt -o f --long force -- "$@")"
     while [[ $1 != -- ]]; do
         case $1 in
             -f|--force) export GITHOOKS_RUN=true; shift;;
